spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: tawkenskiy
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true


# Prometheus configuration
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true

    distribution:
      percentiles-histogram:
        "[http.server.requests]": true




