spring:
  application:
    name: eureka-server




eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30



  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/


  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 5